Tabbar and tiling WMs
martyr-deepin/deepin-terminal-gtk pull request #115
Opened 2019-01-22 14:21 UTC by avently

I added an option to settings window which allows to place tabbar at the bottom of the screen. By default it is disabled. Also users with tiling WMs from the specified list (https://github.com/avently/deepin-terminal/blob/7ce1c52a33c3e7b54ccc414316ea2d46f63cd592/lib/utils.vala#L115) will get expected behaviour of the app. 
Please, check how it looks like in your WM or DE. Mine i3 and XFCE are Ok.
Also I removed a logo in one commit so if you don't like this change it can be easily reverted. 

Next PR will be made for menu. Most painful PR. Before start I want to ask you something. Do you have problems with current menu implementation? For me, this menu starts with delay and cannot be hidden if I will not select anything (right click to show menu, tap on place without menu does not hide it)

2019-01-23 01:56 UTC, BLumia reviewed
@hualet What do you think about adding tilling wm support to deepin-terminal?

2019-01-23 01:56 UTC, BLumia commented on lib/config.vala
> +            check_string("shortcut", "resize_workspace_up", "Ctrl + Alt + Up");
You should probably rebase your code base to linuxdeepin/deepin-terminal:master first, since we already merged your PR about resizing workspace via shortcut.

2019-01-23 02:15 UTC, avently commented on lib/config.vala
> +            check_string("shortcut", "resize_workspace_up", "Ctrl + Alt + Up");
Rebased. Commit still in the list but no changes from it in the PR

2019-01-25 08:08 UTC, hualet commented
@avently can you get us a screenshot of what it is like on your machine? 
I haven't gone thru your PR yet, but there're things need to be corrected I think:
1. removing logo is not acceptable, you should remove that, and please put non-relevant code in another PR in your future contribution, we'll appreciate that.
2. there should not be any merge commit in your PR, please rebase master first.

2019-01-25 09:04 UTC, BLumia commented
@hualet FYI, Screenshot on my machine:

![image](https://user-images.githubusercontent.com/10095765/51735609-d329ff80-20c2-11e9-9aef-6912b067d0cf.png)

2019-01-25 22:42 UTC, avently commented
- logo returned
- normal rebase

2019-01-25 22:56 UTC, avently commented
![screenshot-2019-01-26_014411_203996392](https://user-images.githubusercontent.com/7953703/51777166-d8537280-20f3-11e9-87f0-cb4f829a43cd.png)
![screenshot-2019-01-26_014918_837518743](https://user-images.githubusercontent.com/7953703/51777170-dbe6f980-20f3-11e9-90e3-f1cf1e3bebb4.png)


Top image without compositor
Bottom image WITH compositor (compton)

left from this PR, right official Deepin Terminal without my code

i3 WM

2019-02-14 08:19 UTC, hualet requested changes
Looks good in most part, some details need to be further discussed.

2019-02-14 08:19 UTC, hualet commented on widget/terminal.vala
> +
Is this related to this topic?

2019-02-14 08:19 UTC, hualet commented on widget/preference.vala
> +            tabbar_location_checkbutton = new Widgets.CheckButton();
I don't think we need the UI at the moment since it'll be a visual distraction for normal users, what do you think?

2019-02-14 08:19 UTC, hualet commented on lib/utils.vala
> +private int is_tiling_wm_value = 2;
why not boolean?

2019-03-05 11:29 UTC, avently commented
Oh, didn't see you comments

2019-03-05 11:32 UTC, avently commented on widget/terminal.vala
> +
Yes. There is no menu button (at the right side of the title bar) in tiling WMs so it will be impossible to change theme without this item inside menu shown with right click

2019-03-05 11:34 UTC, avently commented on widget/preference.vala
> +            tabbar_location_checkbutton = new Widgets.CheckButton();
What does you mean by "normal users"? Anyone can choose to show tabbar at the bottom or at default location. No distracion for me:)

2019-03-05 11:35 UTC, avently commented on lib/utils.vala
> +private int is_tiling_wm_value = 2;
https://github.com/linuxdeepin/deepin-terminal/pull/115/files/94654ab50aee6317f1d78ebe900318f80f45af8e#diff-c165190337cc76fa3d07294dfd7c09a1R110

2019-03-13 06:35 UTC, hualet commented on lib/utils.vala
> +private int is_tiling_wm_value = 2;
Make a static boolean variable like `cached` in the function and use that as the do once guardian will be better I think?

2019-03-13 06:38 UTC, hualet commented on widget/preference.vala
> +            tabbar_location_checkbutton = new Widgets.CheckButton();
> What does you mean by "normal users"? Anyone can choose to show tabbar at the bottom or at default location. No distracion for me:)

When I said normal users I mean the users that just leave most of the things as it is as the DE/OS was installed, or at least that users can not use a tiling window manager?

2019-04-18 17:35 UTC, avently commented on lib/utils.vala
> +private int is_tiling_wm_value = 2;
Done. Better?

2019-04-18 17:38 UTC, avently commented on widget/preference.vala
> +            tabbar_location_checkbutton = new Widgets.CheckButton();
Looks like you didn't like this feature or didn't give it a try:) I can't imaging a work with terminal without bottom tabbar. I hope you and your users will find this feature useful. If we will hide it from UI nobody will use it ever

2019-04-19 09:27 UTC, hualet commented on widget/preference.vala
> +            tabbar_location_checkbutton = new Widgets.CheckButton();
I can't say if I like this feature or not because I don't use tiling WM, but I did try it.

Terminal has a title bar at the bottom really doesn't play well with other windows in a non-tiling-wm environment(see the screenshot I attached), so I expect not many people would use it in this way. What do you think?

![image](https://user-images.githubusercontent.com/2023967/56417890-ed413b80-62c7-11e9-8890-5d6744d93074.png)

2019-04-19 11:58 UTC, avently commented on widget/preference.vala
> +            tabbar_location_checkbutton = new Widgets.CheckButton();
@hualet of course, not many people will use it, I agree.
But it can be interesting feature of the terminal which makes it unique for your users. I didn't see the feature anywhere else. Maybe you'll get some of the users of i3wm or other popular solutions. It's sad but Deepin Terminal is not famous and I want it to be changed.
Anyway, what do you want? To remove this toggle from settings?

2019-04-22 06:17 UTC, hualet commented on widget/preference.vala
> +            tabbar_location_checkbutton = new Widgets.CheckButton();
@avently Yeah, I think an option in the conf file is sufficient at the moment :)

2019-04-22 06:21 UTC, hualet commented on widget/preference.vala
> +            tabbar_location_checkbutton = new Widgets.CheckButton();
I did notice someone is moving title bars to the bottom yesterday, https://www.youtube.com/watch?v=bzja9fQWzdA&t=3080s, but I still can't get used to it, sorry :sweat_smile:

2019-04-22 09:42 UTC, avently commented on widget/preference.vala
> +            tabbar_location_checkbutton = new Widgets.CheckButton();
Nice idea, found this code for Firefox: https://gist.github.com/Arty2/e6e61801531ec5ee1f9f
Works Ok. Removed these lines because it breaks custom theme's tabs:
```
#TabsToolbar {
	margin-top: -10px !important;
}
```

>option in the conf file is sufficient

I'll remove option from setings window

2019-04-23 01:28 UTC, hualet commented on widget/preference.vala
> +            tabbar_location_checkbutton = new Widgets.CheckButton();
Thanks.

2019-04-25 10:33 UTC, hualet approved these changes
LGTM

2019-04-25 10:44 UTC, merged