feat: add open in the browser menu item
martyr-deepin/deepin-terminal-gtk pull request #145
Opened 2019-04-13 13:07 UTC by lolimay

- [ ] 实现链接右键菜单项 <kbd>Open in the browser</kbd>
- [] 本地化

不太会本地化😅
请问大佬有空可以在 `i18n`目录下写个简要的 README.md 说明下本地化步骤吗？

**Preview:**
![deepin-screen-recorder_Desktop_20190413210322](https://user-images.githubusercontent.com/32427260/56080172-14af8880-5e30-11e9-8fb5-9e1dc5e28621.gif)

2019-04-14 07:28 UTC, BLumia commented
`_("Open in the browser")` 就可以了，更新翻译只需要更新 pot 文件（有个 `create_pot.sh` 供使用）然后传到 transifex 上去，这个我们会定期做同步。

不过像这样的特性会不会被采纳还得经过产品那边确定是不是可以接受这样的需求，所以还是等一下产品那边的意见吧 :)

2019-04-14 07:33 UTC, lolimay commented
嗯，好的。

2019-04-25 15:10 UTC, hualet commented
有一个 Copy link了，再来一个 Open link 不会好一点么？ 
另外，这个提交应该需要rebase一下了 @lolimay

2019-04-25 15:13 UTC, lolimay commented
> 有一个 Copy link了，再来一个 Open link 不会好一点么？
> 另外，这个提交应该需要rebase一下了 @lolimay

是指把 `Open in the browser` 改成 `Open link` 吗？

2019-04-25 15:15 UTC, BLumia commented
> 有一个 Copy link了，再来一个 Open link 不会好一点么？

#1073 需要产品那边确认一下，以及看看现在的文案有没有问题 :)

2019-04-26 01:06 UTC, hualet commented
> > 有一个 Copy link了，再来一个 Open link 不会好一点么？
> > 另外，这个提交应该需要rebase一下了 @lolimay
> 
> 是指把 `Open in the browser` 改成 `Open link` 吗？

对

2019-04-26 03:16 UTC, wangjia12 commented
文案：
【打开链接】【Open link】
cc @zhuxiujuancindy

2019-04-26 03:27 UTC, BLumia requested changes

2019-04-26 03:27 UTC, BLumia commented on widget/terminal.vala
> +                menu_content.append(new Menu.MenuItem("open", _("Open in the browser")));
按照产品那边给出的文案修改一下就可以了 :)
另外我觉得打开可以放到第一个选项（在copy link上面）

2019-04-26 03:51 UTC, hualet requested changes

2019-04-26 03:51 UTC, hualet commented on widget/terminal.vala
> +                            GLib.AppInfo appinfo = GLib.AppInfo.create_from_commandline("xdg-open '%s'".printf(uri_at_right_press), null, GLib.AppInfoCreateFlags.NONE);
不需要 AppInfo 吧，可以直接使用 `Process::spawn_command_line_sync`之类的，终端代码里面有使用到。

2019-04-26 03:52 UTC, lolimay commented on widget/terminal.vala
> +                            GLib.AppInfo appinfo = GLib.AppInfo.create_from_commandline("xdg-open '%s'".printf(uri_at_right_press), null, GLib.AppInfoCreateFlags.NONE);
好的，我看看 :)

2019-04-26 06:12 UTC, hualet submitted a review, later dismissed

2019-04-26 07:29 UTC, BLumia submitted a review, later dismissed

2019-04-26 11:28 UTC, lolimay commented
https://github.com/linuxdeepin/deepin-terminal/pull/145/commits/009929eabded86cf33405c87617a91e9fe48eef2 仅将 commit message 由 `i18m: update open link` 改成 `i18n: update open link`.

2019-04-26 16:55 UTC, BLumia submitted a review, later dismissed

2019-04-26 16:56 UTC, BLumia commented
😂 您得记得 rebase 一下啊（（（（（

2019-04-27 03:40 UTC, lolimay commented
>  您得记得 rebase 一下啊（（（（（

前辈称呼晚辈“您”，晚辈可真受不住啊 :joy:

请问是 https://github.com/linuxdeepin/deepin-terminal/commit/4bc393110eaf8e8aa3e9c863c2029dccd54bc46e 这样的吗？

2019-04-27 09:28 UTC, BLumia approved these changes

2019-04-27 10:10 UTC, BLumia requested changes
如上 :joy: 抱歉我之前疏漏忘掉了这里提到的那个点。

测试方式是： `echo www.example.com` 然后右键这个链接尝试从菜单中选择你添加的菜单尝试打开。

2019-04-27 10:10 UTC, BLumia commented on widget/terminal.vala
> +                            Process.spawn_command_line_sync("xdg-open '%s'".printf(uri_at_right_press));
:joy: 啊我疏忽了，这里还是要改的。

`xdg-open` 并不能应付没有协议的链接（比如 `www.example.com` ，不带 `http://`），可以考虑使用 [`Gtk.show_uri()`](https://valadoc.org/gtk+-3.0/Gtk.show_uri.html)，另外可以参考下面这部分代码，这是按住 Ctrl 点击时打开的行为：

https://github.com/linuxdeepin/deepin-terminal/blob/7dc5ed977db63b8bf02cc78901d384dadaf1e636/widget/terminal.vala#L169-L180

2019-04-27 10:45 UTC, lolimay commented
> 如上  抱歉我之前疏漏忘掉了这里提到的那个点。
> 
> 测试方式是： `echo www.example.com` 然后右键这个链接尝试从菜单中选择你添加的菜单尝试打开。

谢谢前辈提示 :)

2019-04-27 10:45 UTC, lolimay commented on widget/terminal.vala
> +                            Process.spawn_command_line_sync("xdg-open '%s'".printf(uri_at_right_press));
谢谢前辈提示 :)

2019-04-29 01:31 UTC, snyh commented
可以类似  https://github.com/linuxdeepin/deepin-terminal/pull/149  

直接把open link 功能合并到 open 里去，这样不用修改用户界面和文案。

提交!149时，没看到这个PR ...  



-------------
另外Open in filemanager和这里的几个Open意思是不同的，应该加个分隔符更合适。 open in filemanager是打开当前ctty进程的cwd目录，和终端中出现的文字没有任何关系。

2019-04-29 10:29 UTC, lolimay commented
@BLumia 前辈怎么看？

2019-04-30 03:33 UTC, hualet commented
@snyh 我倒是觉得应该把目前Open的功能合并到 Open in file manager里面，Open link 和 Copy link 应该算到一类是因为他俩都不需要选中。

2019-04-30 04:18 UTC, snyh commented
> @snyh 我倒是觉得应该把目前Open的功能合并到 Open in file manager里面，Open link 和 Copy link 应该算到一类是因为他俩都不需要选中。

- Open in file manager是和当前文字内容没有任何关系，是直接打开当前目录，不论鼠标在哪里。
- Open 合并到 "Open in file manager"，那选中的是一个img, txt然后打开的是文管，怎么打开？
 　或者是用对应的eog,gedit等打开，但显示的却是"in file manager"？

2019-04-30 05:37 UTC, hualet commented
那要不就：

- 新增 Open link (无需选中，支持URI以及URL打开)
- 修改 Open -> Open selected item，功能不变
- 修改 Open in file manager -> Open working directory，功能不变

这样就比较明确了。 @snyh 老大你觉得呢？

2019-04-30 13:11 UTC, BLumia commented
Open link 是新增项。不与任何一项别的合并比较好。

说实话我还真没注意到原有那里有个 Open.. 改成叫 Open selected item 我觉得更好些。

在文件管理器中显示那个文案我觉得没问题（注：Konsole 里叫 `Open File Manager`）。

@snyh @hualet 觉得呢？

另外，就这个 PR 而言， @lolimay 可以考虑只做新增 Open link 的功能（这样可以先 review 先合并，也保证一个 PR 只专注一件事），等具体其他行为讨论确定下来之后我们再在别的新提交里做。

2019-04-30 13:13 UTC, lolimay commented
> Open link 是新增项。不与任何一项别的合并比较好。
> 
> 说实话我还真没注意到原有那里有个 Open.. 改成叫 Open selected item 我觉得更好些。
> 
> 在文件管理器中显示那个文案我觉得没问题（注：Konsole 里叫 `Open File Manager`）。
> 
> @snyh @hualet 觉得呢？
> 
> 另外，就这个 PR 而言， @lolimay 可以考虑只做新增 Open link 的功能（这样可以先 review 先合并，也保证一个 PR 只专注一件事），等具体其他行为讨论确定下来之后我们再在别的新提交里做。

嗯，好的。

2019-05-01 09:24 UTC, lolimay commented on widget/terminal.vala
> +                            Process.spawn_command_line_sync("xdg-open '%s'".printf(uri_at_right_press));
已经重新实现，请 review :)

2019-05-03 11:05 UTC, BLumia approved these changes
LGTM

2019-05-04 15:40 UTC, BLumia commented
看来手动合并有时候不会自动关闭 PR 的样子。

已 merged （ https://github.com/linuxdeepin/deepin-terminal/commit/0e3233e4d3556f99303162f66b7eb1c9fe305792 https://github.com/linuxdeepin/deepin-terminal/commit/6a880e1580d15f3e5e05d6410a7c890f50f8f91d ），整合原有 Open 功能的需求在其他 PR （#149）做就好 :)

2019-05-04 15:40 UTC, closed without merging