fix: make special password for ssh login works.
martyr-deepin/deepin-terminal-gtk pull request #175
Opened 2019-06-09 12:45 UTC by abcfy2

fix #160

2019-06-09 12:48 UTC, abcfy2 commented
修复过程:

将expect中`{}`逃逸变量部分替换为`""`，因为我发现使用了`{}`之后没法逃逸`{}`本身。比如`set var {v\{a\}lue}`这么逃逸的话，得到的变量部分实际为`v\{a\}lue`，所以改用引号赋值变量，这样需要逃逸两个特殊字符`"`引号本身和变量引用字符`$`，通过正则替换掉即可

2019-06-10 03:14 UTC, BLumia approved these changes
LGTM

cc @liuwen123

2019-06-10 05:26 UTC, BLumia requested changes
测试未通过，连接任意远程位置提示 `login_server: 编译正则表达式 (["$\]) (于字符 7 处)时出错：字符类缺少终结的 ]`，应该是正则写错了？

[terminal-build.zip](https://github.com/linuxdeepin/deepin-terminal/files/3270702/terminal-build.zip)

2019-06-10 05:38 UTC, abcfy2 commented
那个`\\`是后来才加上去，想匹配`\`字符本身，看来这个正则经过正则引擎解析之后又变了样了，以前没加最后的`\\`是测试OK的，现在我改下重测下

2019-06-10 05:46 UTC, abcfy2 commented
现在测一下呢？我大概知道是怎么回事了，实际这个正则字符串需要经过两次转义。一次是string本身的转义，交给正则引擎，正则引擎还需要再做一次解析。

所以要匹配`\`这个字符串，在正则引擎看到的字符串必须是`\\`，那么正则字符串必须是`\\\\`

2019-06-10 05:59 UTC, BLumia commented
vala 可以用 `"""` 做 [verbatim string/原始字符串](https://wiki.gnome.org/Projects/Vala/StringSample)。

2019-06-10 06:08 UTC, BLumia approved these changes

2019-06-10 06:09 UTC, merged

2019-06-10 06:09 UTC, abcfy2 commented
哦，原来vala有类似于python的raw string的功能啊，如果改用原始字符串这种形式的话的确对正则友好，不需要考虑正则表达式本身的转义了

2019-06-10 06:11 UTC, BLumia commented
是，不过感觉 vala 这个原始字符串（`"""string"""`）没 c# 的（`@"string"`）看着方便。