Window styling
martyr-deepin/deepin-terminal-gtk pull request #216
Opened 2020-02-07 06:28 UTC by avently

- tabbar_at_the_bottom feature worked bad for environment with compositor running:
  -- draw_titlebar_underline used wrong 'y' coordinate
  -- the whole frame had incorrect dimensions too
- enabled draw_window_above for environment without compositor. Because some important visual elements were missing with disabled compositor
- line drawn under tabbar had incorrect background color. Now it's the same as a color for a side menu's line

I checked that everything is fine in i3wm & newly installed Gnome with tabbar_at_the_bottom enabled & disabled, with compositor & without compositor, with dark & light themes.

PS. there are not much changes I did in window.vala. Git diff looks ugly but it's because I removed top-level `if (screen_monitor.is_composited())` in `draw_window_above()` and adjusted indentation accordingly. So it's easier to check the difference without git diff

2020-02-07 07:04 UTC, avently commented
Does anyone know where the app sets color for GtkPaned's separator? Couldn't find this place. I want to change the color to match `title_line_dark_color` inside config_window

2020-02-13 11:54 UTC, BLumia commented
Sorry I've been busy for a long time for other projects from deepin so I'll try to review this pull request later in this week. Thanks for your patience...

2020-02-16 06:44 UTC, BLumia requested changes
The `title_line_dark_color` is intended so it cannot be changed, the tabbar underline position fix for `tabbar_at_the_bottom=true` looks good to me.

> enabled draw_window_above for environment without compositor. Because some important visual elements were missing with disabled compositor

I did tested this one under deepin with dde-kwin & compositor disabled, but I'm not sure which visual elements were missing, could you provide more details so I can know related code change is okay or not? Thanks.

---------

ps. once again you did multiple changes in a single commit & pull request which makes accepting one of these changes and leaves other change into future discussion not an option, so I really hopes you can try do submit multiple pull request for differencet purpose of changes :joy:

2020-02-16 06:44 UTC, BLumia commented on widget/config_window.vala
> -            title_line_dark_color = Utils.hex_to_rgba("#000000", 0.3);
This color is intended, so we cannot change this one

2020-02-16 07:16 UTC, avently commented on widget/config_window.vala
> -            title_line_dark_color = Utils.hex_to_rgba("#000000", 0.3);
Ok, I'll leave it as it was

2020-02-16 07:20 UTC, BLumia commented
> I want to change the color to match `title_line_dark_color` inside config_window

Actually I'm not fimilar with GTK ui stuff so I also don't know the solution of this question. Although this question is not related to changes in this pull request, I still would like to share some informations which may related to this feature which you are working on.

The current GTK deepin-terminal project starts long times ago by @manateelazycat , and the deepin-terminal project is which he is mainly developed and maintained. Almost all other DDE applications are Qt/C++ based so there are actually no other people also maintain this project. After he leaves deepin few years ago, this project is no longer under actively developed.

Since there are only a few numbers of peoples knows GTK/vala very well, and they also have their own projects to maintain as their daily work, so we can only take our time to maintain this project which mostly are doing bugfixes instead of adding new features/do UI changes and etc.

In the upcoming v20 updates there is a whole new UI re-design by the designer, since most Deepin devs are C++/Qt developer, so actually there is a new terminal app team is working on a Qt/DTK version of the new terminal, which can makes the UI changes and other feature request more easy to do. This project will probably no longer get maintained from Deepin then.

This GTK based deepin-terminal is still a project from deepin, once there are changes related to UI and other stuff, it cannot be merged unless the designer from the company agree with the change. Since it seems you are working on many UI changes with the terminal app, so personally I encourage you create your own fork and the you can focus on your design without bother with waiting for designer's opinion.

That's all what I think it's worth to mention, but anyway, I'd still like to help you review the code and get it merged into the project as long as I can do :)

2020-02-16 08:10 UTC, avently commented
> I did tested this one under deepin with dde-kwin & compositor disabled, but I'm not sure which visual elements were missing, could you provide more details so I can know related code change is okay or not? Thanks.

![screenshot-2020-02-16_101737_366952544](https://user-images.githubusercontent.com/7953703/74600652-77933100-508c-11ea-9cec-d85b3681bd41.png)


> ps. once again you did multiple changes in a single commit & pull request which makes accepting one of these changes and leaves other change into future discussion not an option, so I really hopes you can try do submit multiple pull request for differencet purpose of changes

This phrase triggered me to write a post with size of the screen but when I saw your previous post I started from scratch:)
Ok, I got why you do what you do. 
I will just write here a line from my unpublished answer:
If you feel youself uncomfortable in Vala it doesn't mean I made a complex PR (I'm a copy-paste expert in Vala so my code can't be complex).

But anyway I undertsand the situation now and thank you for clarification. It's a bit sad that this terminal will be abandoned because I really like it and it's an application I use the most. I hope the next terminal will have the same or better UI and functionality. 

Can you give a link to the new terminal or it's not for public yet?

2020-02-16 08:58 UTC, BLumia commented
> If you feel youself uncomfortable in Vala it doesn't mean I made a complex PR (I'm a copy-paste expert in Vala so my code can't be complex).

No I'm good with your patch :)

Your patch is not complex but still doing multiple works/fixes in a single commit, for example in this case I think I'm okay to approve your tabbar underline change but put the `draw_window_above` change on-hold, which is not possible if you do it in a single commit. The atomic commit concept applies everywhere ([KDE's commit policy for example](https://community.kde.org/Policies/Commit_Policy)) and that's intended to deal with this kinds of issue.

For the long explain above, I means once there are changes related to UI behavior, I cannot made the decision just by me since it's a commercial-driven product which the behavior is mainly managed by the company. And also since deepin decided to make a new DTK based terminal app, so if you plan to do heavy changes related to UI behavior, I suggest you to create a fork and then you can focus on your changes.

2020-02-16 09:08 UTC, BLumia commented
> ![](https://user-images.githubusercontent.com/7953703/74600652-77933100-508c-11ea-9cec-d85b3681bd41.png)

I think maybe I missed something, the titlebar border line color differences, and also tabbar underline differences, which these two differences are not related to compositor. Is there any other differences I missed? Thanks.

> Can you give a link to the new terminal or it's not for public yet?

Almost all v20 projects' source code are still not public yet, the source may get ready in next month but still no promise. I'll let you know if you're interested :)

2020-02-16 09:08 UTC, avently commented
>  so if you plan to do heavy changes related to UI behavior, I suggest you to create a fork and then you can focus on your changes

I'm not planning to make heavy changes after your post about new terminal. I'll you this one for now until I'll find a better alternative (I think it's impossible but who knows).

Since I made nothing serious with UI but fixed issues your users have I expect it to be merged some day after your designer approves it. If it's not possible that's ok. I'll focus on other things I have in my life instead of contributing here.

2020-02-16 09:14 UTC, avently commented
> I think maybe I missed something, the titlebar border line color differences, and also tabbar underline differences, which these two differences are not related to compositor. Is there any other differences I missed? Thanks.

Yep, we have differences because for some reason in `draw_window_above` had a check `if (screen_monitor.is_composited()` which disabled all those changes for tabbar lines. That's why I changed the method `draw_window_above` to enable the code for non-composited environments. I have no idea why it was disabled because it is not related to compositor as you mentioned already.

2020-02-16 09:27 UTC, BLumia commented
> I'm not planning to make heavy changes after your post about new terminal. I'll you this one for now until I'll find a better alternative (I think it's impossible but who knows).

New terminal project doesn't means the existed GTK based deepin-terminal will no-longer exist, you can still use it if you like :)

> > I think maybe I missed something, the titlebar border line color differences, and also tabbar underline differences, which these two differences are not related to compositor. Is there any other differences I missed? Thanks.
> 
> Yep, we have differences because for some reason in `draw_window_above` had a check `if (screen_monitor.is_composited()` which disabled all those changes for tabbar lines. That's why I changed the method `draw_window_above` to enable the code for non-composited environments. I have no idea why it was disabled because it is not related to compositor as you mentioned already.

Okay I'll take another look later :)

2020-02-17 02:45 UTC, BLumia approved these changes
Hi and I did another look about the draw_window_above change and that part is also okay for me!

2020-02-17 02:48 UTC, merged