[Feature Request] Close terminal tab with Scroll Wheel #88
martyr-deepin/deepin-terminal-gtk pull request #92
Opened 2018-12-24 11:09 UTC by sylank

Close terminal tab with Scroll Wheel

2018-12-25 01:17 UTC, BLumia requested changes
A couple of inline comments.

2018-12-25 01:17 UTC, BLumia commented on lib/config.vala
> +                config_file.set_string("shortcut", "rename_title", "Alt + t");
Please keep a commit atomic, don't make any change not related to the current Pull Request

2018-12-25 01:17 UTC, BLumia commented on lib/config.vala
> +                init_config();
Seems this is not a necessary change, keep the old code as-is unless it's really need to be modify :)

2018-12-25 09:54 UTC, sylank commented on lib/config.vala
> +                config_file.set_string("shortcut", "rename_title", "Alt + t");
sorry, accidentally I copied this changes from my another branch :)

2018-12-25 09:56 UTC, sylank commented on lib/config.vala
> +                init_config();
I just wanted to clean that if statement, but yes this modification is not part of this scope. reverted :)

2018-12-26 02:11 UTC, BLumia approved these changes
Looks good.

2018-12-26 10:09 UTC, merged